### ISSUE TITLE
Office in text on home page

### ISSUE THREAD

**Issue by BigActual** [realbig/kwaske_th_17#2]
![](https://ibin.co/3tDKmkSUaTbx.png)

Can't tell if maybe this is some rogue white copy?

**Comment by joelworsham** [comment]
Does this consistently happen for you? What device, OS, browser? I do not see this.

![](https://d.pr/i/ZEDr16+)

**Comment by BigActual** [comment]
It is consistent. Samsung Galaxy Note 5 at 2,560x1,440

**Comment by joelworsham** [comment]
There is absolutely nothing abnormal about the text or font here. This has to be a phone-specific rendering issue. I can't really do anything about it :/

**Comment by BigActual** [comment]
It's the word Construction in white. does that help at least identify where it's coming from?

**Comment by BigActual** [comment]
Ahhh, It's the title from Concrete Work & Driveway Construction

**Comment by joelworsham** [comment]
Whaaaat. Is it still happening? i globally modified text size, which may fix it. Again, give it a hard refresh (shift + F5 I think)

**Comment by BigActual** [comment]
I'll never be able to tell. I shortened the page title to just Concrete. and I'm not going back.
