### ISSUE TITLE
Page and Post Page Title Graphic Adjustment

### ISSUE THREAD

**Issue by BigActual** [realbig/kwaske_th_17#3]
Could you modify the page title so that it is set the full width of the content area instead of moving down a row? It would then reside above the sidebar too, which is fine. Perhaps, like this?
https://d.pr/i/iydEdZ

**Comment by BigActual** [comment]
Almost. Is it maybe just a CSS adjustment?
https://d.pr/i/w8LvtQ

**Comment by joelworsham** [comment]
what the... can you hard refresh? That's not what I see:

![](https://d.pr/i/U3jJrT+)

**Comment by BigActual** [comment]
Success. It's working now.
